# Generated by Django 5.1 on 2024-09-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='request_type',
        ),
    ]
