# Generated by Django 5.1 on 2024-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loanapplication_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='request_type',
            field=models.CharField(choices=[('FUND', 'Fund Request'), ('LOAN', 'Loan Request')], default='LOAN', max_length=10),
        ),
    ]
